Add message component
egardner/mediawiki-extensions-MachineVision pull request #6
Opened 2020-04-02 22:32 UTC by AnneTee

Simple message component that supports the 4 existing message types. No support yet for custom or no icons. This feels like an appropriate place to use `<slot />` to me, but let me know if you don't think so!

2020-04-02 22:56 UTC, egardner commented
A reusable message component is absolutely the right use-case for slots!

2020-04-03 15:03 UTC, egardner requested changes
Looks good, just a few minor comments below.

2020-04-03 15:03 UTC, egardner commented on resources/components/base/Message.vue
> +			iconMap: {
I understand why you need an icon map to reference here, but if this object is not going to change then it should not be in state. I don't think we'll be adding, changing, or removing keys or values here, right?

My instinct here would be to treat the `iconMap` as a constant and move it outside of the reactive state entirely – it could be declared above module.exports (`var ICON_MAP = {...}`).

Then I'd suggest referencing this value in a computed property called `icon` since you won't have access to this non-component variable in the template:

```
computed: {
    icon: function () {
        return ICON_MAP[ this.type ];
    }
}
```

Then your template code around line 8 could look like this:

```
<icon v-bind:icon="icon" />
```

2020-04-03 15:03 UTC, egardner commented on resources/components/base/Message.vue
> +			v-bind:class="'oo-ui-image-' + type"
Since this component already has one computed property to return a simple class name (`typeClass`), I'd recommend treating all of them that way and moving this concatenation into a new computed prop (`imageClass` or `iconClass` maybe). I think doing the aria attributes in-line above is fine though.

2020-04-03 15:03 UTC, egardner commented on resources/components/base/Message.vue
> +			iconMap: {
In general, I think it's good to be aggressive in keeping state to an absolute minimum; more state leads to more complexity. This component really just needs props and derived attributes. By getting rid of state, we create an opportunity to further optimize this component by making it functional, if we ever decide we need to.

2020-04-03 15:03 UTC, egardner commented on resources/components/base/Message.vue
> +		typeClass() {
Now that @catrope's linter rules have been merged, computed prop and method names should be written in ES5 syntax: `typeClass: function() {}` etc.

2020-04-03 15:51 UTC, AnneTee commented
Thanks for the helpful feedback @egardner!

2020-04-03 15:56 UTC, egardner commented on resources/components/base/Icon.vue
> +		builtInClasses() {
Looks like these props still need the ES5 format applied.

2020-04-03 16:47 UTC, egardner approved these changes

2020-04-03 16:48 UTC, merged